---
- name: Configuracion Basica del SO
  hosts: all
  gather_facts: true
  become: true

  tasks:
    #    - name: Aplicar Role de Configuraciones Basicas
    #      ansible.builtin.include_role:
    #        name: common
    #      tags: ["common"]
    #
    #    - name: Aplicar Role de Configuraciones Firewall
    #      ansible.builtin.include_role:
    #        name: firewall
    #      tags: ["firewall"]

    - name: Aplicar Role de Configuraciones etcd
      ansible.builtin.include_role:
        name: etcd
      tags: ["etcd"]
