---
# Configuración de FQDN
domain_name: labrhel.com # example.com

# Configuracion del sistema
selinux_state: permissive
selinux_policy: targeted
timezone: America/Bogota

# Configuracion de red
network_interface: enp1s0
virtual_ip: 192.192.20.81

# COnfiguracion de POstgreSQL
postgres_version: 17
postgres_user: postgres
postgres_data_dir: /u01/pgsql/17
postgres_bin_dir: /usr/pgsql-17/bin
