---
# create_tables
- name: Configurar sesión para DDL
  community.postgresql.postgresql_query:
    db: "{{ db_name }}"
    query: |
      SET statement_timeout = 0;
      SET lock_timeout = 0;
      SET client_encoding = 'UTF8';
      SET search_path TO {{ db_schema }}, public;
    login_host: "{{ ansible_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: 5432

- name: Crear tabla 'value_types'
  community.postgresql.postgresql_table:
    db: "{{ db_name }}"
    name: value_types
    owner: "{{ db_user }}"
    columns:
      - name character varying(50) NOT NULL
      - regex character varying(100) NOT NULL
      - description character varying(255) NOT NULL
      - author character varying(50) NOT NULL
      - creation_date integer NOT NULL
      - last_update integer
    login_host: "{{ ansible_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: 5432
    state: present
  register: value_table_created

- name: Crear tablas 'document_types'
  community.postgresql.postgresql_table:
    db: "{{ db_name }}"
    name: document_types
    owner: "{{ db_user }}"
    columns:
      - name character varying(50) NOT NULL
      - description character varying(255) NOT NULL
      - author character varying(50) NOT NULL
      - lifecycle_status character varying(20) DEFAULT 'PUBLISHED'::character varying
      - retention smallint DEFAULT 1 NOT NULL
      - creation_date integer NOT NULL
      - last_update integer
    login_host: "{{ ansible_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: 5432
    state: present
  register: table_created
#  notify: Agregar constraint document_types

# Tabla formalities
- name: Crear tabla formalities
  community.postgresql.postgresql_table:
    db: "{{ db_name }}"
    name: formalities
    owner: "{{ db_user }}"
    columns:
      - name character varying(63) NOT NULL
      - description character varying(255) NOT NULL
      - lifecycle_status character varying(20) DEFAULT 'PUBLISHED'::character varying NOT NULL
      - creation_date integer NOT NULL
      - last_update integer
      - author character varying(50) NOT NULL
    login_host: "{{ ansible_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: 5432
#  notify: Agregar constraints formalities

# Tabla metadata
- name: Crear tabla metadata
  community.postgresql.postgresql_table:
    db: "{{ db_name }}"
    name: metadata
    owner: "{{ db_user }}"
    columns:
      - name character varying(30) NOT NULL
      - document_type_name character varying(50) NOT NULL
      - min_cardinality integer DEFAULT 1 NOT NULL
      - creation_date integer NOT NULL
      - last_update integer
      - metadata smallint DEFAULT 0 NOT NULL
    login_host: "{{ ansible_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: 5432
#  notify: Agregar constraints metadata

# Tabla template_labels
- name: Crear tabla template_labels
  community.postgresql.postgresql_table:
    db: "{{ db_name }}"
    name: template_labels
    owner: "{{ db_user }}"
    columns:
      - template_name character varying(50) NOT NULL
      - template_version integer NOT NULL
      - name character varying(30) NOT NULL
      - value_type text NOT NULL
      - size character varying(50) NOT NULL
      - description character varying(255) NOT NULL
      - author character varying(50) NOT NULL
      - min_cardinality smallint DEFAULT 1 NOT NULL
      - creation_date integer NOT NULL
      - last_update integer
      - metadata smallint DEFAULT 0 NOT NULL
    login_host: "{{ ansible_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: 5432
#  notify: Agregar constraints template_labels

# Tabla templates
- name: Crear tabla templates
  community.postgresql.postgresql_table:
    db: "{{ db_name }}"
    name: templates
    owner: "{{ db_user }}"
    columns:
      - name character varying(50) NOT NULL
      - version integer DEFAULT 1 NOT NULL
      - lifecycle_status character varying(20) DEFAULT 'PUBLISHED'::character varying NOT NULL
      - type character varying(10) DEFAULT 'PDF'::character varying NOT NULL
      - author character varying(50) NOT NULL
      - valid_for integer
      - creation_date integer NOT NULL
      - last_update integer
      - retention integer
      - description character varying(255) NOT NULL
      - file_content bytea NOT NULL
    login_host: "{{ ansible_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: 5432
#  notify: Agregar constraints templates

# Aplicar constraints
- name: Aplicar constraints
  ansible.builtin.include_tasks: apply_constraints.yml
  tags: [apply_constraints]
