---
# tasks file for roles/etcd
- name: Habiliar y configurar etcd
  block:
    - name: Mostrar información del sistema
      ansible.builtin.debug:
        msg:
          - "Distribution: {{ ansible_distribution }}"
          - "Major Version: {{ ansible_distribution_major_version }}"
          - "Package Manager: {{ ansible_pkg_mgr }}"

    - name: Descargar claves GPG PostgreSQL
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - url: https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL
          dest: /etc/pki/rpm-gpg/PGDG-RPM-GPG-KEY-RHEL
        - url: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG
          dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG

    - name: Importar claves GPG PostgreSQL
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      loop:
        - /etc/pki/rpm-gpg/PGDG-RPM-GPG-KEY-RHEL
        - /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG

    - name: Instalar Repo PostgreSQL si el gestor de paquetes es DNF
      ansible.builtin.dnf:
        name:
          - "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        state: present
        update_cache: true
      when: ansible_pkg_mgr == 'dnf'
      register: basic_packages
      failed_when: basic_packages is failed

    - name: Instalar Repo PostgreSQL si el gestor de paquetes es YUM
      ansible.builtin.yum:
        name:
          - "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        state: present
        update_cache: true
      when: ansible_pkg_mgr == 'yum'
      register: basic_packages
      failed_when: basic_packages is failed

    - name: Actualizar caché DNF
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_pkg_mgr == 'dnf'

    - name: Verificar si el repositorio PostgreSQL está instalado
      ansible.builtin.stat:
        path: "/etc/yum.repos.d/pgdg-redhat-all.repo"
      register: pgdg_repo_file

    #    - name: Habilitar repositorio (extras) si el gestor de paquetes es DNF - pgdg-rhel{{ ansible_distribution_major_version }}
    #      ansible.builtin.shell: |
    #        set -o pipefail
    #        dnf config-manager --set-enabled pgdg-rhel{{ ansible_distribution_major_version }}-extras
    #      register: pgdg_extras
    #      changed_when: pgdg_extras.rc == 0
    #      failed_when: pgdg_extras.rc != 0
    #      when: ansible_pkg_mgr == 'dnf'
    #
    #    - name: Habilitar repositorio (extras) si el gestor de paquetes es YUM - pgdg-rhel{{ ansible_distribution_major_version }}
    #      ansible.builtin.shell: |
    #        set -o pipefail
    #        yum config-manager --set-enabled pgdg-rhel{{ ansible_distribution_major_version }}-extras
    #      register: pgdg_extras
    #      changed_when: pgdg_extras.rc == 0
    #      failed_when: pgdg_extras.rc != 0
    #      when: ansible_pkg_mgr == 'yum'

    # Habilitar el repositorio extras
    - name: Habilitar repositorio extras PostgreSQL
      block:
        - name: Habilitar repo extras PostgreSQL con dnf_config_manager
          community.general.dnf_config_manager:
            name: "pgdg-rhel{{ ansible_distribution_major_version }}-extras"
            state: enabled
          when:
            - ansible_pkg_mgr == 'dnf'
          register: enable_repo_result
          until: enable_repo_result is succeeded

      rescue:
        - name: Método alternativo - Habilitar con command
          ansible.builtin.command:
            cmd: "{{ ansible_pkg_mgr }} config-manager --set-enabled pgdg-rhel{{ ansible_distribution_major_version }}-extras"
          when: ansible_pkg_mgr in ['dnf', 'yum']
          register: enable_cmd_result
          changed_when: enable_cmd_result.rc == 0

    - name: Habilitar repositorio pgdg-rhel8-extras si el gestor de paquetes es YUM
      ansible.builtin.yum_repository:
        name:
          - pgdg-rhel{{ ansible_distribution_major_version }}-extras
        state: present
      when: ansible_pkg_mgr == 'yum'
      register: pgdg_extras
      failed_when: pgdg_extras is failed

    - name: Instalar 'etcd' si el gestor de paquetes es DNF
      ansible.builtin.dnf:
        name:
          - etcd
        state: present
      when: ansible_pkg_mgr == 'dnf'
      register: pgdg_extras
      failed_when: pgdg_extras is failed

    - name: Instalar 'etcd' si el gestor de paquetes es YUM
      ansible.builtin.yum:
        name:
          - etcd
        state: present
      when: ansible_pkg_mgr == 'yum'
      register: pgdg_extras
      failed_when: pgdg_extras is failed

    - name: Obtener Informacion de '/etc/etcd/etcd.conf'
      ansible.builtin.stat:
        path: /etc/etcd/etcd.conf
      register: stat_etcd_file

    - name: Crear copia de seguridad del archivo de configuracion inicial
      ansible.builtin.copy:
        src: /etc/etcd/etcd.conf
        dest: /etc/etcd/etcd.conf.orig
        remote_src: true
        force: true
        owner: "{{ stat_etcd_file.stat.pw_name }}"
        group: "{{ stat_etcd_file.stat.gr_name }}"
        mode: "{{ stat_etcd_file.stat.mode }}"
      register: etcd_backup
      failed_when: etcd_backup is failed

    - name: Configurar 'etcd'
      ansible.builtin.template:
        src: etcd.conf.j2
        dest: /etc/etcd/etcd.conf
        owner: "{{ stat_etcd_file.stat.pw_name }}"
        group: "{{ stat_etcd_file.stat.gr_name }}"
        mode: "{{ stat_etcd_file.stat.mode }}"
      register: etcd_backup
      failed_when: etcd_backup is failed

    - name: Reiniciar etcd
      ansible.builtin.systemd:
        name: etcd
        state: restarted
        enabled: true
        daemon_reload: true
      register: etcd_service
      failed_when: etcd_service is failed

    - name: Pausa para 'etcd'
      ansible.builtin.pause:
        seconds: 5

    - name: Esperar a que 'etcd' incie
      ansible.builtin.wait_for:
        port: 2379
        state: started
        timeout: 60
      register: etcd_wait
      failed_when: etcd_wait is failed

    - name: Obtener información de usuarios
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        - "{{ ansible_usr }}"
        - "{{ postgres_user }}"
      register: user_info
      check_mode: true
      changed_when: false

    - name: Configurar variables de entorno de etcd
      ansible.builtin.blockinfile:
        path: "{{ item.home }}/.bash_profile"
        block: |
          # etcd cluster endpoints
          {% for host in groups['postgresql_servers'] %}
          export {{ host }}={{ hostvars[host]['ansible_host'] }}
          {% endfor %}
          export ENDPOINTS={% for host in groups['postgresql_servers'] %}${{ host }}:2379{% if not loop.last %},{% endif %}{% endfor %}
        create: true
        mode: "0644"
        owner: "{{ item.name }}"
        group: "{{ item.group }}"
      loop: "{{ user_info.results }}"
      when: item.home is defined

    - name: Ejecutar etcdctl con variables de entorno configuradas
      ansible.builtin.shell: |
        set -o pipefail
        etcdctl endpoint status --write-out=table --endpoints="$ENDPOINTS"
      environment:
        ENDPOINTS: "{{ my_endpoints }}"
      vars:
        my_endpoints: "{% for host in groups['postgresql_servers'] %}{{ host }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
      changed_when: false
      register: etcdctl_out

    #    - name: Ejecutar etcdctl con variables de entorno configuradas
    #      ansible.builtin.shell: |
    #        . /home/{{ ansible_usr }}/.bash_profile
    #        etcdctl endpoint status --write-out=table --endpoints="$ENDPOINTS"
    #      args:
    #        executable: /bin/bash
    #      changed_when: false
    #      register: etcdctl_out

    - name: Debug - Ejecutar etcdctl
      ansible.builtin.debug:
        var: etcdctl_out.stdout_lines
  rescue:
    - name: Notificar fallo en la configuración de etcd
      ansible.builtin.fail:
        msg: "Fallo en la configuración de etcd. El proceso se ha detenido."
