---
# tasks file for roles/common
- name: Configuracion del Sistema
  block:
    - name: Configurar SELinux
      ansible.posix.selinux:
        state: "{{ selinux_state }}"
        policy: "{{ selinux_policy }}"
      register: selinux_config
      failed_when: selinux_config is failed

    - name: Reiniciar el servidor si SELinux lo requiere
      ansible.builtin.reboot:
        msg: "Reinicio tras cambio de SELinux"
        connect_timeout: 5
        reboot_timeout: 600
        post_reboot_delay: 5
      when: selinux_config.changed # noqa: no-handler
      register: selinux_reboot
      failed_when: selinux_reboot is failed

    - name: Configurar Zona Horaria
      community.general.timezone:
        name: "{{ timezone }}"
      register: timezone_config
      failed_when: timezone_config is failed
  rescue:
    - name: Notificar fallo en la Configuracion FQDN
      ansible.builtin.fail:
        msg: "Fallo en la configuracion del FQDN, Proceso detenido"

- name: Actualizar Dependencias y Paquetes del SO
  block:
    - name: Actualizar todos los paquetes del Servidor si el gestor de paquetes es DNF
      ansible.builtin.dnf:
        name:
          - "*"
        state: latest
        update_cache: true
        update_only: true
      when: ansible_pkg_mgr == 'dnf'
      register: package_update
      failed_when: package_update is failed

    - name: Actualizar todos los paquetes del Servidor si el gestor de paquetes es YUM
      ansible.builtin.yum:
        name:
          - "*"
        state: latest
        update_cache: true
        update_only: true
      when: ansible_pkg_mgr == 'yum'
      register: package_update
      failed_when: package_update is failed

    #     - name: Descargar la clave GPG para RHEL
    #       ansible.builtin.get_url:
    #         url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    #         dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8"
    #         mode: "0644"
    #
    #     - name: Importar la clave GPG para RHEL
    #       ansible.builtin.rpm_key:
    #         key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    #         state: present

    - name: Instalar Paquetes viables si el gestor de paquetes es DNF
      ansible.builtin.dnf:
        name:
          - dnf-utils
          - epel-release
          #          - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
          - python3-pip
        state: present
      when: ansible_pkg_mgr == 'dnf'
      register: basic_packages
      failed_when: basic_packages is failed

    - name: Instalar yum-utils y Paquetes viables si el gestor de paquetes es YUM
      ansible.builtin.yum:
        name:
          - yum-utils
          - epel-release
          #          - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
          - python3-pip
        state: present
      when: ansible_pkg_mgr == 'yum'
      register: basic_packages
      failed_when: basic_packages is failed
  rescue:
    - name: NOtificar fallo en la configuracion SELinux
      ansible.builtin.fail:
        msg: "Fallo la actualzacion del Sistema del sistema."

- name: Crear usuario postgres y configurar permisos
  block:
    - name: Crear usuario postgres
      ansible.builtin.user:
        name: "{{ postgres_user }}"
        shell: /bin/bash
        createhome: true
        state: present
        password: "{{ postgres_password }}"
      register: postgres_user_result
      failed_when: postgres_user_result is failed

    - name: Configurar privilegios sudo para el usuario postgres
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/postgres
        line: "postgres ALL=(ALL) NOPASSWD:ALL"
        state: present
        mode: "0440"
        create: true
        validate: "visudo -cf %s"
      register: sudo_config
      failed_when: sudo_config is failed
  rescue:
    - name: Notificar fallo en la configuración del usuario postgres
      ansible.builtin.fail:
        msg: "Fallo en la configuración del usuario postgres."

- name: Configuracion /etc/hosts
  block:
    #     - name: Obtener el nombre del Host actual
    #       ansible.builtin.command:
    #         cmd: hostname
    #       register: current_hostname
    #       changed_when: false
    #
    #     - name: Configurar el Hostname
    #       ansible.builtin.hostname:
    #         name: "{{ inventory_hostname }}.{{ domain_name }}" # VALIDAR VARS DEL DOMINIO
    #       register: hostname_result
    #       failed_when: hostname_result is failed
    #       when: current_hostname.stdout != inventory_hostname + '.' + domain_name
    #
    #     - name: Verificar que el FQDN del servidor esta OK
    #       ansible.builtin.command:
    #         cmd: hostname -f
    #       register: fqdn_check
    #       changed_when: false
    #      failed_when: fqdn_check.stdout != inventory_hostname + '.' + domain_name

    - name: Obtener permisos actuales del - /etc/hosts
      ansible.builtin.stat:
        path: /etc/hosts
      register: hosts_stat

    - name: Configurar DNS Interno - /etc/hosts
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        owner: "{{ hosts_stat.stat.pw_name }}"
        group: "{{ hosts_stat.stat.gr_name }}"
        mode: "{{ hosts_stat.stat.mode }}"
      register: hosts_file
      failed_when: hosts_file is failed
  rescue:
    - name: Notificar fallo en la Configuracion /etc/hosts
      ansible.builtin.fail:
        msg: "Fallo en la configuracion del /etc/hosts, Proceso detenido"
